### ISSUE TITLE
Add to awesome-zeebe?

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe-hazelcast-exporter#1]
Would love to add this to the https://github.com/zeebe-io/awesome-zeebe, what do you think?

**Comment by saig0** [comment]
Yes! But before I want to release a first version, including a C# connector.

**Comment by menski** [comment]
Cool :sunglasses: 

> including a C# connector.

Interesting :slightly_smiling_face:

**Comment by saig0** [comment]
Done zeebe-io/awesome-zeebe/pull/2
