### ISSUE TITLE
Allow to override default base image and destination image

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-hazelcast-exporter#81]
It should be possible to define a different base image for Zeebe and a different destination image for the Docker image being generated.

This solves the current problem that the registry is hard-coded into the image names. Overriding the mage names will allow to use different registries or purely local images.

**Comment by saig0** [comment]
The Jib plugin allows overriding these properties already. You can use
```
-Djib.from.image=
-Djib.to.image=
```
to configure the source and target image.

Do you need more than this?
